In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df = pd.DataFrame(data.data , columns = data.feature_names)

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['target'] = data.target

In [7]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [8]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [9]:
# we want to understand binary classification here so dropping the tagert with value 2

df_final = df[df['target']!=2]

In [10]:
df_final

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [11]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  100 non-null    float64
 1   sepal width (cm)   100 non-null    float64
 2   petal length (cm)  100 non-null    float64
 3   petal width (cm)   100 non-null    float64
 4   target             100 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 4.3 KB


In [12]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [13]:
from sklearn.model_selection import  train_test_split
x = df_final.iloc[:,:-1]
y = df_final.iloc[:,-1]
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2)

In [14]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
64                5.6               2.9                3.6               1.3
8                 4.4               2.9                1.4               0.2
78                6.0               2.9                4.5               1.5
49                5.0               3.3                1.4               0.2
7                 5.0               3.4                1.5               0.2
..                ...               ...                ...               ...
14                5.8               4.0                1.2               0.2
88                5.6               3.0                4.1               1.3
58                6.6               2.9                4.6               1.3
85                6.0               3.4                4.5               1.6
20                5.4               3.4                1.7               0.2

[80 rows x 4 columns]

In [15]:
y_train

64    1
8     0
78    1
49    0
7     0
     ..
14    0
88    1
58    1
85    1
20    0
Name: target, Length: 80, dtype: int32

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
classifier = LogisticRegression()

In [18]:
classifier

LogisticRegression()

In [19]:
classifier.fit(x_train , y_train)

LogisticRegression()

In [20]:
y_pred = classifier.predict(x_test)

In [21]:
# by default cuttoff is 0.5
classifier.predict_proba(x_test)

array([[0.01015775, 0.98984225],
       [0.98024397, 0.01975603],
       [0.02294043, 0.97705957],
       [0.00548055, 0.99451945],
       [0.00438992, 0.99561008],
       [0.98086223, 0.01913777],
       [0.00247761, 0.99752239],
       [0.01680479, 0.98319521],
       [0.08506009, 0.91493991],
       [0.03438996, 0.96561004],
       [0.98560142, 0.01439858],
       [0.97831008, 0.02168992],
       [0.96716888, 0.03283112],
       [0.00531059, 0.99468941],
       [0.94957883, 0.05042117],
       [0.00584217, 0.99415783],
       [0.00795953, 0.99204047],
       [0.00845911, 0.99154089],
       [0.0228517 , 0.9771483 ],
       [0.0697389 , 0.9302611 ]])

In [52]:
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score , roc_curve , auc

In [54]:
print(confusion_matrix(y_test , y_pred))

[[ 6  0]
 [ 0 14]]


In [56]:
acc = accuracy_score(y_test , y_pred)
acc

1.0

In [58]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        14

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [66]:
classifier.predict_proba(x_test)[: ,-1] # this is the predicted probability for 1 class

array([0.98984225, 0.01975603, 0.97705957, 0.99451945, 0.99561008,
       0.01913777, 0.99752239, 0.98319521, 0.91493991, 0.96561004,
       0.01439858, 0.02168992, 0.03283112, 0.99468941, 0.05042117,
       0.99415783, 0.99204047, 0.99154089, 0.9771483 , 0.9302611 ])

In [68]:
y_predict_proba = classifier.predict_proba(x_test)[: ,-1] 

In [78]:
print(roc_curve(y_test , y_predict_proba)) # it will return a TPR FPR with different cuttoff of probability

(array([0., 0., 0., 1.]), array([0.        , 0.07142857, 1.        , 1.        ]), array([       inf, 0.99752239, 0.91493991, 0.01439858]))


In [80]:
fpr , tpr , threshold = roc_curve(y_test , y_predict_proba)

In [82]:
fpr

array([0., 0., 0., 1.])

In [84]:
tpr

array([0.        , 0.07142857, 1.        , 1.        ])

In [86]:
threshold

array([       inf, 0.99752239, 0.91493991, 0.01439858])

In [88]:
auc(fpr, tpr)

1.0