In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification

In [3]:
x,y =make_classification(n_samples= 1000 , n_features=10 , n_classes= 2 , n_redundant= 5 , n_informative= 5 , random_state=1)

In [4]:
x

array([[ 2.56999479, -0.13019997,  3.16075093, ..., -1.93094078,
         3.26130366,  2.05692145],
       [ 0.34129317,  2.51321418, -0.80416572, ...,  6.24734437,
        -1.92769365,  2.9503149 ],
       [ 2.27539972,  3.36561455,  0.17164362, ...,  2.74693781,
         0.13492444,  2.00339547],
       ...,
       [ 0.5234359 ,  1.90466429,  0.93243365, ...,  1.53945231,
         1.90646166,  1.99458587],
       [ 1.33747921,  3.25859684,  0.78792366, ...,  5.18788314,
        -0.82071083,  3.51411431],
       [-0.98534299,  0.83919047,  2.5820803 , ...,  3.04705685,
         0.66885641,  3.32838496]])

In [5]:
y

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =1)

In [7]:
#  now we are going to do hyper parameter tuning
# grid search cv and randomised search cv
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression()

In [8]:
params = {'penalty': ['l1','l2','elastic net'],
          'C':[1,7,14,20,30]}
params

{'penalty': ['l1', 'l2', 'elastic net'], 'C': [1, 7, 14, 20, 30]}

In [9]:
clf = GridSearchCV(classifier,param_grid = params,cv = 5 ,verbose=2)
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 7, 14, 20, 30],
                         'penalty': ['l1', 'l2', 'elastic net']},
             verbose=2)

In [11]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ...........................C=1, penalty

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 7, 14, 20, 30],
                         'penalty': ['l1', 'l2', 'elastic net']},
             verbose=2)

In [13]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [18]:
clf.best_estimator_

LogisticRegression(C=1)

In [28]:
clf.best_score_

0.80625

In [30]:
# first approch for modeling and prediction value is using the best_Estimator.predict or we can create a seperate model 
y_pred = clf.best_estimator_.predict(x_test)


In [32]:
# another approch is that we create a seperate model with the best parameter

In [36]:
model = LogisticRegression(C=1,penalty='l2')  

In [38]:
model.fit(x_train,y_train)

LogisticRegression(C=1)

In [40]:
y_pred_2 = model.predict(x_test)

In [44]:
print(f"accuracy of model is {model.score(x_train,y_train)*100:.2f}")

accuracy of model is 81.12


In [52]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
acc = accuracy_score(y_test,y_pred_2)
con = confusion_matrix(y_test,y_pred_2)
cl = classification_report(y_test,y_pred_2)
print(f"accuracy is {acc*100:.2f}")
print(f"confusion_matrix is \n {con}")
print(f"classification report is \n {cl}")

accuracy is 82.50
confusion_matrix is 
 [[84 10]
 [25 81]]
classification report is 
               precision    recall  f1-score   support

           0       0.77      0.89      0.83        94
           1       0.89      0.76      0.82       106

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.82       200



In [60]:
pred_proba = model.predict_proba(x_test)

In [62]:
print(pred_proba)

[[0.01589785 0.98410215]
 [0.84266072 0.15733928]
 [0.70451437 0.29548563]
 [0.86543984 0.13456016]
 [0.4363369  0.5636631 ]
 [0.91047374 0.08952626]
 [0.03392216 0.96607784]
 [0.68783065 0.31216935]
 [0.88083681 0.11916319]
 [0.03768722 0.96231278]
 [0.92471858 0.07528142]
 [0.57431996 0.42568004]
 [0.26644873 0.73355127]
 [0.76243298 0.23756702]
 [0.40880764 0.59119236]
 [0.3155212  0.6844788 ]
 [0.04282863 0.95717137]
 [0.13068134 0.86931866]
 [0.02514161 0.97485839]
 [0.93007644 0.06992356]
 [0.54540378 0.45459622]
 [0.03750493 0.96249507]
 [0.18078577 0.81921423]
 [0.90346854 0.09653146]
 [0.08076816 0.91923184]
 [0.44235007 0.55764993]
 [0.85423236 0.14576764]
 [0.53766208 0.46233792]
 [0.50778359 0.49221641]
 [0.83037355 0.16962645]
 [0.75287617 0.24712383]
 [0.22146763 0.77853237]
 [0.90525433 0.09474567]
 [0.35047955 0.64952045]
 [0.03636204 0.96363796]
 [0.01875864 0.98124136]
 [0.00985743 0.99014257]
 [0.94950949 0.05049051]
 [0.9692858  0.0307142 ]
 [0.51728284 0.48271716]


In [88]:
from sklearn.model_selection import RandomizedSearchCV
randomCV = RandomizedSearchCV(classifier ,param_distributions=params,cv=5,verbose = 2,n_iter=10)
randomCV.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END ...................................C=20, penalty=l2; total time=   0.0s
[CV] END ...................................C=20, penalty=l2; total time=   0.0s
[CV] END ...................................C=20, penalty=l2; total time=   0.0s
[CV] END ...................................C=20, penalty=l2; total time=   0.0s
[CV] END ...................................C=20, penalty=l2; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ...........................C=1, penalty=elastic net; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 7, 14, 20, 30],
                                        'penalty': ['l1', 'l2', 'elastic net']},
                   verbose=2)

In [90]:
randomCV.get_params

<bound method BaseEstimator.get_params of RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 7, 14, 20, 30],
                                        'penalty': ['l1', 'l2', 'elastic net']},
                   verbose=2)>

In [92]:
randomCV.estimator

LogisticRegression()

In [94]:
randomCV.best_estimator_

LogisticRegression(C=20)

In [96]:
randomCV.best_score_

0.80625